### ISSUE TITLE
[ebean-agent] ToStringBuilder enhancement does not use toString() of the abstract class

### ISSUE THREAD

**Issue by nPraml** [ebean-orm/ebean#2672]
Hello @rbygrave ,

we have a problem with the ToStringBuilder.
We have an abstract class:

```java
@DocStore
@Inheritance
@DiscriminatorColumn(name = "kind")
public abstract class CustomProperty<T> {
        ....
        public abstract Object getValue();

   	@Override
	public final String toString() {
		return String.valueOf(getValue());
	}
        ....
}
```

and we have some child classes, e.g. `DoubleCustomProperty`,  `StringCustomProperty`, etc.

```java
@DocStore
@DiscriminatorValue("string")
public class StringCustomProperty extends CustomProperty<String> {
        ....
        private String value;

        public String getValue {
               return value;
        }
        ....
}
```

## Expected behavior

```java
StringCustomProperty prop = new StringCustomProperty("test");

assertThat(prop.ToString()).isEqualTo("test");
```

## Actual behavior

```java
StringCustomProperty prop = new StringCustomProperty("test");

assertThat(prop.ToString()).isEqualTo("StringCustomProperty@0(value:test)");
```

If we make toString in CustomProperty final, we get an exception, that a final method will be overwritten in StringCustomProperty.

Can you help to fix this?

Kind regards,
Noemi

**Comment by rbygrave** [comment]
It looks like there is insufficient information here.  There are no annotations on the classes here ... which means there is not going to be any enhancement applied and no toString() implementation added.

**Comment by nPraml** [comment]
sorry @rbygrave , I forgot the annotations. I corrected it in the code examples

**Comment by rbygrave** [comment]
Hi @nPraml ... the example still doesn't look right in that we can't do `new StringCustomProperty("test");` on an abstract class ?

**Comment by nPraml** [comment]
sorry @rbygrave , it was a copy-paste mistake, StringCustomProperty is not abstract

**Comment by rbygrave** [comment]
There is no `@Entity` annotation here (or `@MappedBy`, `@Embedded` or `@EmbeddedId`) - so I still don't think that is a failing test case there.

**Comment by rbygrave** [comment]
The `@Docstore` annotation is enough to make it an get entity in terms of enhancement which includes the toString() generation.

**_I am not able to reproduce though._**  See https://github.com/ebean-orm/ebean-agent/commit/8f15acc68ad5832dc3d7507e998bb7487ee099b7 ... you'll need to create a PR that modifies that test to fail if you can.

Note that the ebean-agent does have a check that it will only add a `toString()` implementation IF there isn't already an implementation and it doesn't extend a type that is an entity and has a `toString()` implementation.  In this case CustomProperty has an implementation, so I would expect that check to work and for the test to pass (not reproduce the issue).

**Next steps:**
- create a PR to ebean-agent that modifies that test I've just added to get it to fail

**Comment by rbygrave** [comment]
Hang on ... I might be able to reproduce.

**Comment by rbygrave** [comment]
Reproduced and fixed with: https://github.com/ebean-orm/ebean-agent/issues/180

**Notes:**
- I needed to bump ebean-version.mf **ebean-version to 133** to enable the "toString" feature (it requires that version of ebean)
- The underlying issue was that the ClassMetaReaderVisitor was not detecting/setting classMeta.setHasToString();
- A trick to note wrt debugging enhancement is that `mvn clean process-test-classes` will perform the enhancement without running tests. If people are messing with ebean-agent putting in debug lines etc to see what enhancement is doing (because it's hard to debug otherwise).

**Comment by nPraml** [comment]
@rbygrave , thank you for the fix!
